package com.wm.dataobject;

public class ProjectFileDownloadDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_info.file_id
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_info.download_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    private Integer downloadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_info.read_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    private Integer readCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_info.file_id
     *
     * @return the value of project_file_download_info.file_id
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_info.file_id
     *
     * @param fileId the value for project_file_download_info.file_id
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_info.download_count
     *
     * @return the value of project_file_download_info.download_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_info.download_count
     *
     * @param downloadCount the value for project_file_download_info.download_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_info.read_count
     *
     * @return the value of project_file_download_info.read_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_info.read_count
     *
     * @param readCount the value for project_file_download_info.read_count
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }
}