package com.wm.dataobject;

import java.util.Date;

public class ProjectFileDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.id
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.project_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.file_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.file_size
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.file_path
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.project_description
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.if_cc
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private Byte ifCc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_info.upload_time
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    private Date uploadTime;
    private String ccUser;
    private String uploadUser;
    private ProjectFileDownloadDO projectFileDownloadDO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.id
     *
     * @return the value of project_file_info.id
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.id
     *
     * @param id the value for project_file_info.id
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.project_name
     *
     * @return the value of project_file_info.project_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.project_name
     *
     * @param projectName the value for project_file_info.project_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.file_name
     *
     * @return the value of project_file_info.file_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.file_name
     *
     * @param fileName the value for project_file_info.file_name
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.file_size
     *
     * @return the value of project_file_info.file_size
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.file_size
     *
     * @param fileSize the value for project_file_info.file_size
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.file_path
     *
     * @return the value of project_file_info.file_path
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.file_path
     *
     * @param filePath the value for project_file_info.file_path
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.project_description
     *
     * @return the value of project_file_info.project_description
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.project_description
     *
     * @param projectDescription the value for project_file_info.project_description
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.if_cc
     *
     * @return the value of project_file_info.if_cc
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public Byte getIfCc() {
        return ifCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.if_cc
     *
     * @param ifCc the value for project_file_info.if_cc
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setIfCc(Byte ifCc) {
        this.ifCc = ifCc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_info.upload_time
     *
     * @return the value of project_file_info.upload_time
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_info.upload_time
     *
     * @param uploadTime the value for project_file_info.upload_time
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    public void setCcUser(String ccUser) {
        this.ccUser = ccUser;
    }

    public String getCcUser() {
        return ccUser;
    }

    public void setUploadUser(String uploadUser) {
        this.uploadUser = uploadUser;
    }

    public String getUploadUser() {
        return uploadUser;
    }

    public ProjectFileDownloadDO getProjectFileDownloadDO() {
        return projectFileDownloadDO;
    }

    public void setProjectFileDownloadDO(ProjectFileDownloadDO projectFileDownloadDO) {
        this.projectFileDownloadDO = projectFileDownloadDO;
    }
}