package com.wm.dataobject;

import java.util.Date;

public class ProjectFileDownloadLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_log.id
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_log.file_id
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_log.user_id
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_log.user_name
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file_download_log.time
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    private Date time;

    private ProjectFileDO projectFileDO;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_log.id
     *
     * @return the value of project_file_download_log.id
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_log.id
     *
     * @param id the value for project_file_download_log.id
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_log.user_name
     *
     * @return the value of project_file_download_log.user_name
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_log.user_name
     *
     * @param userName the value for project_file_download_log.user_name
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file_download_log.time
     *
     * @return the value of project_file_download_log.time
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file_download_log.time
     *
     * @param time the value for project_file_download_log.time
     *
     * @mbg.generated Sun Jun 09 14:56:07 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    public ProjectFileDO getProjectFileDO() {
        return projectFileDO;
    }

    public void setProjectFileDO(ProjectFileDO projectFileDO) {
        this.projectFileDO = projectFileDO;
    }
}