package com.wm.dataobject;

public class WebsiteFilePathDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_file_path.website_id
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    private Integer websiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_file_path.file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_file_path.website_id
     *
     * @return the value of website_file_path.website_id
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_file_path.website_id
     *
     * @param websiteId the value for website_file_path.website_id
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_file_path.file_path
     *
     * @return the value of website_file_path.file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_file_path.file_path
     *
     * @param filePath the value for website_file_path.file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}