package com.wm.dao;

import com.wm.dataobject.ProjectFileCcDO;

public interface ProjectFileCcDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int insert(ProjectFileCcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int insertSelective(ProjectFileCcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    ProjectFileCcDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectFileCcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_cc_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int updateByPrimaryKey(ProjectFileCcDO record);
}