package com.wm.dao;

import com.wm.dataobject.ProjectFileDownloadDO;

public interface ProjectFileDownloadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int insert(ProjectFileDownloadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int insertSelective(ProjectFileDownloadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    ProjectFileDownloadDO selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectFileDownloadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_download_info
     *
     * @mbg.generated Sun Apr 14 15:11:58 CST 2019
     */
    int updateByPrimaryKey(ProjectFileDownloadDO record);

    void addDownloadOrReadTimes(ProjectFileDownloadDO projectFileDownloadDO);
}