package com.wm.dao;

import com.github.pagehelper.Page;
import com.wm.controller.viewobject.ProjectFileVO;
import com.wm.dataobject.ProjectFileDO;

public interface ProjectFileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    int insert(ProjectFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    int insertSelective(ProjectFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    ProjectFileDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file_info
     *
     * @mbg.generated Sun Apr 14 12:09:09 CST 2019
     */
    int updateByPrimaryKey(ProjectFileDO record);

    Page<ProjectFileDO> selectAllCc(Integer userId);

    Page<ProjectFileDO> selectBySearch(ProjectFileDO record);
}