package com.wm.dao;

import com.wm.dataobject.RoleInfoDO;

import java.util.List;

public interface RoleInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    int insert(RoleInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    int insertSelective(RoleInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    RoleInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    int updateByPrimaryKeySelective(RoleInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbg.generated Sat Apr 13 23:13:44 CST 2019
     */
    int updateByPrimaryKey(RoleInfoDO record);

    List<RoleInfoDO> selectAll();
}