package com.wm.dao;

import com.wm.dataobject.WebsiteFilePathDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WebsiteFilePathDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    int deleteByPrimaryKey(WebsiteFilePathDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    int insert(WebsiteFilePathDOKey record);

    int insertByBatch(@Param("filesPath") List<WebsiteFilePathDOKey> filesPath);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_file_path
     *
     * @mbg.generated Sat Jun 01 14:26:29 CST 2019
     */
    int insertSelective(WebsiteFilePathDOKey record);

    int deleteByWebsiteId(@Param("id")Integer id);

    List<String> selectById(@Param("id")Integer id);
}